contact_links:
  - name: Question/Discussion
    url: https://github.com/jbangdev/jbang/discussions/new
    about: I have a question or topic to discuss which is not a bug nor new feature.
  - name: JBang Zulip Chat
    url: https://jbangdev.zulipchat.com/#narrow/channel/457549-dev
    about: If you prefer live chat with the developers, we hang out on Zulip.
